name: C/C++ CI

on:
  push:
    branches:
      - master
      - glm-test
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
